// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvyq66Sd89axkX5lwA5-EGHrVQ3OTYwBk',
    appId: '1:153585194025:web:b53f9260d628f68b143838',
    messagingSenderId: '153585194025',
    projectId: 'todo-store-726bf',
    authDomain: 'todo-store-726bf.firebaseapp.com',
    storageBucket: 'todo-store-726bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkttXPKZBbqx-e7Nf89vla9GoRPXmNC9s',
    appId: '1:153585194025:android:2fcd82f7b00d382a143838',
    messagingSenderId: '153585194025',
    projectId: 'todo-store-726bf',
    storageBucket: 'todo-store-726bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4QE1tMiV3cTHkl919N20UIrlAvH2K8zE',
    appId: '1:153585194025:ios:7b1325b0a6723487143838',
    messagingSenderId: '153585194025',
    projectId: 'todo-store-726bf',
    storageBucket: 'todo-store-726bf.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4QE1tMiV3cTHkl919N20UIrlAvH2K8zE',
    appId: '1:153585194025:ios:1bf3bb2a77dc19d3143838',
    messagingSenderId: '153585194025',
    projectId: 'todo-store-726bf',
    storageBucket: 'todo-store-726bf.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
